POST https://api.github.com/repos/Memodz/gh-actions-demo/dispatches
Content-Type: application/json
Accept: application/vnd.github+json
Authorization: Bearer ${{ secrets.TOKEN }}

{
    "event_type": "on-demand-test",
    "client_payload": {
        "status": "completed"
    }
}
