POST https://api.github.com/repos/Memodz/gh-actions-demo/dispatches
Content-Type: application/json
Accept: application/vnd.github+json
Authorization: Bearer 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

{
    "event_type": "on-demand-test",
    "client_payload": {
        "status": "completed"
    }
}
