name: Hello World
on: push
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line scirpt
        run: echo "Hello, World! welcome to my first GitHub Actions workflow"
        
