name: Hello World
on: 
  push:
    branches: [main]
    paths-ignore:
      - ".github/workflows/*.yaml"
  pull_request:
    branches: [main]

  repository_dispatch:
    types: ["on-demand-test"]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello, World! welcome to my first GitHub Actions workflow"
  second-job:
    runs-on: windows-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo "This job runs on ${{runner.os}}"
        
